#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025 Urutau-Ltd <softwarelibre@urutau-ltd.org>
#
#   , _ ,      _    _            _                     _ _      _
#  ( o o )    | |  | |          | |                   | | |    | |
# /'` ' `'\   | |  | |_ __ _   _| |_ __ _ _   _ ______| | |_ __| |
# |'''''''|   | |  | | '__| | | | __/ _` | | | |______| | __/ _` |
# |\\'''//|   | |__| | |  | |_| | || (_| | |_| |      | | || (_| |
#    """       \____/|_|   \__,_|\__\__,_|\__,_|      |_|\__\__,_|
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_VERSION="v1.0.0"

# Represents the AppImage file to be downloaded from the
# network
readonly TUTA_FILENAME='tutanota-desktop-linux.AppImage'

# Represents the URL where the AppImage file can be downloaded
readonly TUTA_URL="https://app.tuta.com/desktop/${TUTA_FILENAME}"

# Represents the place where the AppImage file is going to be saved
# after downloading it
readonly TUTA_DIR="${HOME}/.local/sbin"

# Represents the whole path to the downloaded AppImage
readonly TUTA_PATH="${TUTA_DIR}/${TUTA_FILENAME}"

# Represents the .desktop file path, this is used for most desktop environments
# to list the application as usable. However, some desktop environments don't
# recognize these files if they are symlinks or if the Exec= directive is
# a symlink itself
readonly TUTA_DESKTOP="${XDG_DATA_HOME:-$HOME/.local/share}/applications/tutanota-desktop.desktop"

# Represents the configuration directory for the Tuta App. The AppImage searches
# and writes to this location various chrome-related files
readonly TUTA_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/tutanota-desktop/"

# Represents the integration path which is a text file with the path to
# the downloaded AppImage
readonly TUTA_INTEGRATION="${XDG_CONFIG_HOME:-$HOME/.config}/tuta_integration"

# Related to TUTA_INTEGRATION. This points to the file itself.
readonly TUTA_INTEGRATION_FILE="${TUTA_INTEGRATION}/no_integration"

# The directory where the logs of this script will be stored. This is used to
# track down errors that happen inside the Guix Shell command.
readonly LOG_DIR="$HOME/.var/guix-tuta"

# Related to LOG_DIR. It's the log file itself.
readonly LOG_FILE="${LOG_DIR}/tuta-guix-launcher.log"

# BEGIN COLOR CODES
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly BLUE='\033[0;34m'
readonly RESET='\033[0m'
# END COLOR CODES

DEBUG_MODE=0
FORCE_DOWNLOAD=0
CHECK_MODE=0

readonly USER_ID=$(id -u)
readonly USERBUS="/run/user/$USER_ID/bus"

function _log() {
    local -r color="$1"
    local -r message="$2"
    printf "${color}===> %s${RESET}\n" "$message" >&2
}

function _info() { _log "$GREEN" "$*"; }
function _warn() { _log "$YELLOW" "WARN: $*"; }
function _error() { _log "$RED" "FATAL: $*"; exit 1; }
function _check() { _log "$BLUE" "CHECK: $*"; }
function _debug() {
    if [[ "${DEBUG_MODE}" -eq 1 ]]; then
        _log "$BLUE" "DEBUG: $*"
    fi
}

function _usage() {
    cat <<EOF >&2
    tuta - $SCRIPT_VERSION
    
    GNU Bash script to ease the use of Tuta inside GNU Guix with FHS containers
    long options are NOT supported

    Usage: ${0##*/} [-dhv]

    Options:
        -d    Force the AppImage download even if it already exists.
        -c    Check the current installation status.
        -v    Enable verbose output mode.
        -h    Print this help screen.
    
EOF
    exit 0
}

while getopts ':dvhc' opt; do
    case "$opt" in
        d) FORCE_DOWNLOAD=1 ;;
        v) DEBUG_MODE=1 ;;
        c) CHECK_MODE=1 ;;
        h) _usage ;;
        ?) _error "Unknown option -$OPTARG. Use -h or --help for guidance." ;;
        *) _error "How did you get here!?" ;;
    esac
done

function _prepare_appimage() {
    _debug "Preparing AppImage environment."
    
    local REQUIRED_DIRS=(
        "$TUTA_DIR"
        "$TUTA_CONF"
        "$LOG_DIR"
        "$TUTA_INTEGRATION"
    )
   
    for dir in "${REQUIRED_DIRS[@]}"; do
        if [[ ! -d "$dir" ]]; then
            _warn "Required directory at ${dir} wasn't found! Creating it..."
        fi
    done

    if [[ -d "$TUTA_INTEGRATION" ]]; then
        if [[ ! -f "$TUTA_INTEGRATION_FILE" ]]; then
            _warn "Tuta integration is not disabled! Disabling it for you..."
            touch "$TUTA_INTEGRATION_FILE"
            echo "$TUTA_PATH" >> "$TUTA_INTEGRATION_FILE"
        else
             _info "Tuta integration is disabled! (This is OK)"
        fi
    fi

    if [[ ! -f "$TUTA_PATH" ]] || [[ "$FORCE_DOWNLOAD" -eq 1 ]]; then
        if [[ ! -f "$TUTA_PATH" ]]; then
            _info "AppImage not found. Downloading from tuta.com..."
        else
            _warn "Downloading by force!"
        fi

        if curl -fL -o "$TUTA_PATH" "$TUTA_URL"; then
            _info "Download successful. Validating permissions..."
            chmod +x "$TUTA_PATH" || _error "(chmod +x) failed to grant permissions to Tuta AppImage!"
            _info "Permissions: (755) granted to AppImage."
        else
            _warn "Download failed. Removing potentially corrupted file: ${TUTA_PATH}"
            rm -f "$TUTA_PATH"
            _error "Failed to download Tuta from: ${TUTA_URL}."
        fi
    else
        _info "Tuta AppImage found at: ${TUTA_PATH}. No download is required!"
        if [[ ! -x "$TUTA_PATH" ]]; then
            _warn "Tuta AppImage found but is NOT executable. Granting permissions..."
            chmod +x "$TUTA_PATH" || _error "(chmod +x) failed to grant permissions to existing Tuta AppImage!"
            _info "Permissions: (755) granted to existing AppImage."
        else
            _info "Tuta AppImage is already executable. Ready to run."
        fi
    fi
}

function _execute_guix() {
    _info "Invoking a new Guix FHS container..."
    
    local GUIX_EXPOSE_DESKTOP=""
    
    if [[ -f "$TUTA_DESKTOP" ]]; then
        _info "Patched desktop file found at ${TUTA_DESKTOP}. Exposing to shell..."
        GUIX_EXPOSE_DESKTOP="--expose=${TUTA_DESKTOP}"
    else
        _warn "Tuta desktop file NOT found at ${TUTA_DESKTOP}"
        _warn "The AppImage will keep spamming the 'desktop integration' dialog until it finds this file!"
        _warn "Omitting --expose for desktop file"
    fi
    
    _debug "Exposed directory for AppImage: ${TUTA_DIR}"
    _debug "Exposed .desktop argument: ${GUIX_EXPOSE_DESKTOP}"
    _debug "Running with user d-bus at: $USERBUS"

    setsid guix shell --container --network --emulate-fhs \
        --development ungoogled-chromium gcc-toolchain libsecret \
        --preserve='^DISPLAY$' \
        --preserve='^XAUTHORITY$' \
        --expose="$XAUTHORITY" \
        --preserve='^DBUS_' \
        --expose='/var/run/dbus' \
        --expose='/sys/dev' \
        --expose='/sys/devices' \
        --expose="$USERBUS" \
        --expose='/dev/dri' \
        --expose="$TUTA_DIR" \
        --share="$TUTA_CONF" \
        --expose="$TUTA_INTEGRATION" \
        --expose="$TUTA_INTEGRATION_FILE" \
        "$GUIX_EXPOSE_DESKTOP" \
        -- \
        "$TUTA_PATH" --appimage-extract-and-run > "$LOG_FILE" 2>&1 &

    local PID=$!
    _info "Tuta started at PID: ${PID}. Process has been detached (setsid)."
    disown -h "%${PID}" 2>/dev/null || true
}

function _check_install() {
    _check "Checking script dependencies..."
    
    if command -v curl &> /dev/null; then
        _info "✓ curl is available"
    else
        _error "✗ curl is unavailable. (Required for downloading AppImage)"
    fi
    
    if ! command -v guix &> /dev/null; then
        _error "✗ This script is for GNU Guix systems only!"
        exit 1
    fi
    
    _check "Checking files and directories..."
    
    if [[ -d "$TUTA_DIR" ]]; then
        _info "✓ Target dir: $TUTA_DIR exists on this user's home"
    else
        _warn "✗ Target dir: $TUTA_DIR is unavailable. It will be created at runtime"
    fi

    _check "AppImage file: $TUTA_PATH"
    
    if [[ -f "$TUTA_PATH" ]]; then
         _info  "✓ AppImage was found at this user's home"
         
         if [[ -x "$TUTA_PATH" ]]; then
             _info  "✓ Tuta AppImage is executable"
         else
             _warn "✗ Tuta AppImage lacks neccessary permissions"
         fi 

         local SIZE
         SIZE=$(du -h "$TUTA_PATH" | awk '{print $1}')
         _info "AppImage size: $SIZE"
    else
        _warn "✗ Tuta AppImage was not found. Will be downloaded at runtime"
    fi

    _check ".desktop launcher: $TUTA_DESKTOP"
    
    if [[ -f "$TUTA_DESKTOP" ]]; then
         _info  "✓ Desktop launcher found. A --expose= arg will be added to the run command"
    else
        _warn "✗ Desktop launcher not found, Tuta might nag you with a popup when starting"
        _info "The --expose= arg for the desktop launcher will be omitted on the run command"
    fi

    _check "Checking D-Bus & Xserver..."

    if [[ -S "$USERBUS" ]]; then
        _info "✓ D-Bus (User): Active socket found at $USERBUS."
    else
        _warn "✗ D-Bus (User): Unable to find a user dbus socket. The app MIGHT not work!"
    fi
    
    if [[ -n "${DISPLAY:-}" ]]; then
        _info "✓ DISPLAY: ${DISPLAY} (Xserver display found)."
    else
        _warn "✗ DISPLAY: Not set. Tuta won't show or launch if it lacks a display"
    fi

    _check "--- END OF STATE CHECKING, EXITING ---"
    exit 0

}

function _main() {
    _debug "Debug mode is enabled!."
    
    if [[ "${CHECK_MODE}" -eq 1 ]]; then
        _check_install
    fi

    _info "Starting Tuta service."

    _prepare_appimage

    _execute_guix

    _info "Guix shell container with Tuta is up and running!"
}

_main
